#!/usr/bin/env bash
# Build the public demo FROM the product's own UI.
#
# The demo is not a fork. It is internal/web/ui/index.html — the exact file the binary
# serves — with one script appended that answers DB.req in the browser instead of over a
# socket. There is no second copy of the interface to keep in step, which means the demo
# cannot drift from the product, which is the whole point.
#
#   ./demo/build-demo.sh            -> dist/demo/index.html
set -euo pipefail
cd "$(dirname "$0")/.."

SRC=internal/web/ui/index.html
OUT=dist/demo
mkdir -p "$OUT"

[[ -f "$SRC" ]] || { echo "!! $SRC missing"; exit 1; }
grep -q '__invosDemo' "$SRC" || {
  echo "!! $SRC has no demo hook — DB.req must call window.__invosDemo."
  echo "   Without it this build would produce a page that talks to a server that is not there."
  exit 1
}

# The demo store goes in BEFORE the app's own script runs, because the app fetches on
# load. Appending it at the end would mean the first requests fire against nothing.
python - "$SRC" "$OUT/index.html" <<'PY'
import sys, io, re
src, out = sys.argv[1], sys.argv[2]
html = io.open(src, encoding='utf-8').read()
store = io.open('demo/demo-store.js', encoding='utf-8').read()

# Marketing metadata differs from the product's: this page IS public and SHOULD be
# indexed and shareable, where the station's own page must never be either.
html = html.replace(
    '<meta name="robots" content="noindex, nofollow, noarchive, noimageindex">',
    '<meta name="robots" content="index, follow">')
html = html.replace('<title>INV.OS — workshop inventory terminal</title>',
                    '<title>INV.OS — live demo · workshop inventory terminal</title>')

banner = (
  '<script>/* INV.OS demo build — generated by demo/build-demo.sh from the product UI.\n'
  '   Do not edit this file; edit internal/web/ui/index.html or demo/demo-store.js. */</script>\n'
  '<script>\n' + store + '\n</script>\n'
)

# Immediately before the app's own script block, which is the last one in the file.
i = html.rindex('<script>')
html = html[:i] + banner + html[i:]
io.open(out, 'w', encoding='utf-8', newline='\n').write(html)
print("  wrote %s (%d KB)" % (out, len(html.encode('utf-8')) // 1024))
PY

cat > "$OUT/.nojekyll" <<'EOF'
EOF

echo "==> demo built from $SRC"
echo "    open it directly (file://) or serve $OUT for GitHub Pages"
